# Generated by Django 5.0.6 on 2024-06-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
